import { useEffect, useRef, useState } from "react";

interface ScrollFramesProps {
  /** URL prefix before the zero-padded 1-based index, e.g. "/scroll-frames/frame-". */
  basePath?: string;
  /** Total number of frames in the sequence. */
  count?: number;
  /** File extension without the dot (webp; swap to "jpg" for a JPEG set). */
  ext?: string;
  /** Zero-pad width for the index (frame-0001 -> pad 4). */
  pad?: number;
  /** Optional poster still shown until the first frame is ready. Omit to let
   * the #f4eadd base show through (matches the old ScrollVideo behavior). */
  poster?: string;
}

// Frames are generated by scripts/extract-scroll-frames.sh from the SAME
// CloudFront hero video (same footage). Defaults match a 72-frame set.
const DEFAULTS = { basePath: "/scroll-frames/frame-", count: 72, ext: "webp", pad: 4 };
// Preserved EXACTLY from the video-decoding ScrollVideo so the scrub feels
// identical — same scroll smoothing and same DPR cap.
const LERP = 0.12;
const MAX_CONCURRENT = 6;

/** object-cover: scale the source up to cover the dest, centre-crop. Identical
 * math to the old ScrollVideo, so framing/crop is pixel-for-pixel the same. */
function coverRect(sw: number, sh: number, dw: number, dh: number) {
  const scale = Math.max(dw / sw, dh / sh);
  const w = sw * scale;
  const h = sh * scale;
  return { x: (dw - w) / 2, y: (dh - h) / 2, w, h };
}

/**
 * Fixed, full-bleed scroll-scrubbed background rendered from a PRE-RENDERED
 * image sequence (the "Apple product page" technique) — a drop-in replacement
 * for the video-decoding ScrollVideo. There is no <video>, no blob fetch, no
 * requestVideoFrameCallback, no createImageBitmap-from-video, and no low/high-
 * end branching: page scroll maps to a frame index (lerp-smoothed with the same
 * 0.12 factor), and the already-decoded <img> for that frame is drawn to a
 * canvas with the same object-cover math, DPR cap, poster-first paint, and
 * 500ms crossfade. Static images have no codec/decode differences between
 * browsers, so it is smooth and identical on Chrome/Safari/iOS/low-end.
 *
 * Kept as a separate export so it can be activated by swapping one import in
 * home.tsx once the frames exist in public/scroll-frames/.
 */
export function ScrollFrames({
  basePath = DEFAULTS.basePath,
  count = DEFAULTS.count,
  ext = DEFAULTS.ext,
  pad = DEFAULTS.pad,
  poster,
}: ScrollFramesProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [posterVisible, setPosterVisible] = useState(true);
  const [canvasReady, setCanvasReady] = useState(false);

  const targetProgress = useRef(0);
  const smoothed = useRef(0);
  const dpr = Math.min(window.devicePixelRatio || 1, 2);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let disposed = false;

    const url = (i: number) => `${basePath}${String(i + 1).padStart(pad, "0")}.${ext}`;
    const imgs: (HTMLImageElement | null)[] = new Array(count).fill(null);
    const loaded = new Array<boolean>(count).fill(false);
    const started = new Array<boolean>(count).fill(false);
    let anyLoaded = false;
    let inFlight = 0;

    const currentIdx = () => Math.min(count - 1, Math.max(0, Math.round(smoothed.current * (count - 1))));

    // Preload with bounded concurrency, always taking the not-yet-started frame
    // nearest the current scroll position first, then filling the rest.
    function pump() {
      if (disposed) return;
      while (inFlight < MAX_CONCURRENT) {
        const cur = currentIdx();
        let pick = -1;
        let best = Infinity;
        for (let i = 0; i < count; i++) {
          if (started[i]) continue;
          const d = Math.abs(i - cur);
          if (d < best) {
            best = d;
            pick = i;
          }
        }
        if (pick < 0) break;
        started[pick] = true;
        inFlight++;
        const im = new Image();
        im.decoding = "async";
        const done = (ok: boolean) => {
          inFlight--;
          if (ok) {
            loaded[pick] = true;
            imgs[pick] = im;
            if (!anyLoaded) {
              anyLoaded = true;
              setPosterVisible(false);
              setCanvasReady(true);
            }
          }
          pump();
        };
        im.onload = () => done(true);
        im.onerror = () => done(false); // tolerate a missing frame (404)
        im.src = url(pick);
      }
    }

    let needRedraw = true;
    function sizeCanvas() {
      const w = window.innerWidth;
      const h = window.innerHeight;
      canvas!.width = Math.round(w * dpr);
      canvas!.height = Math.round(h * dpr);
      canvas!.style.width = `${w}px`;
      canvas!.style.height = `${h}px`;
      needRedraw = true;
    }
    sizeCanvas();
    window.addEventListener("resize", sizeCanvas);

    function readScroll() {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      targetProgress.current = max > 0 ? Math.min(1, Math.max(0, window.scrollY / max)) : 0;
    }
    readScroll();
    window.addEventListener("scroll", readScroll, { passive: true });

    // Nearest already-loaded frame to `idx`, so the canvas never blanks while
    // the exact target frame is still downloading.
    function nearestLoaded(idx: number) {
      if (loaded[idx]) return idx;
      for (let d = 1; d < count; d++) {
        if (idx - d >= 0 && loaded[idx - d]) return idx - d;
        if (idx + d < count && loaded[idx + d]) return idx + d;
      }
      return -1;
    }

    let raf = 0;
    let lastPumpIdx = -1;
    let lastDrawn = -1;
    function frame() {
      raf = requestAnimationFrame(frame);
      smoothed.current += (targetProgress.current - smoothed.current) * LERP;
      const idx = currentIdx();
      if (idx !== lastPumpIdx) {
        lastPumpIdx = idx;
        pump(); // re-prioritise the loader as the viewer scrolls
      }
      const use = nearestLoaded(idx);
      if (use >= 0 && (use !== lastDrawn || needRedraw)) {
        const im = imgs[use]!;
        const r = coverRect(im.naturalWidth, im.naturalHeight, canvas!.width, canvas!.height);
        ctx!.clearRect(0, 0, canvas!.width, canvas!.height);
        ctx!.drawImage(im, r.x, r.y, r.w, r.h);
        lastDrawn = use;
        needRedraw = false;
      }
    }
    frame();
    pump();

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", sizeCanvas);
      window.removeEventListener("scroll", readScroll);
    };
  }, [basePath, count, ext, pad, dpr]);

  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-0 z-0 overflow-hidden bg-[#f4eadd]"
    >
      {poster && (
        <img
          src={poster}
          alt=""
          className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${
            posterVisible ? "opacity-100" : "opacity-0"
          }`}
        />
      )}
      <canvas
        ref={canvasRef}
        className={`absolute inset-0 h-full w-full transition-opacity duration-500 ${
          canvasReady ? "opacity-100" : "opacity-0"
        }`}
      />
    </div>
  );
}
